### ISSUE TITLE
So many latency

### ISSUE THREAD

**Issue by DoctorGuidance** [NabiKAZ/HamsterKombat-API#6]
Hi
Thank you for you project,

Buy daily cipher and combo seems have many hours delay!

The combo comes at 12:00 UTC, so it must be there in 12:05 UTC
And you have to make a dictionary file to list all cards names as they are in game, so when we request for combo cards, We must know what name of card do we receive, so we will use our works and codes on it, for example we add the image and other data to it and post it to channel. so we need to know what are list of cards name responded. 

and morse code come at 19 UTC I think!

**1- can you update the json as fast as possible? or not.**
**2- can you make a list of cards? and only use the exact card names!**

**I give you the cards names here: (updated 2024-08-05 - 07:00 am UTC)**

### PR&Team
Support Team 
HamsterBook 
X 
Cointelegraph 
HamsterTube 
HamsterGram 
TikTok 
Coindesk 
Influencers 
CEO 
IT Team 
Marketing 
Partnership program 
Product Team 
BisDev Team 
Two Factor Auth 
UX and UI Team 
Security Team 
QA team 
Antihacking shield 
Risk managment 
Security Audition 
Anonymous transactions 
Blocking suspecioius 
Tokenomics expert 
Consensus explorer 
VC labs 
complience oficer 
Welcome to Amsterdam 
Development hub Mumbai 
Data Center Tokyo 
Leaderboards 
Minigame	

### Markets:
Fan Tokens 
Staking 
BTC Pairs 
ETH Pairs 
Top 10 CMC Pairs 
GameFI Tokens 
DeFi 2.0 Tokens 
SocialFi tokens 
Meme Coins 
Shit Coins 
Margin Trading x10 
Margin Trading x20 
Margin Trading x30 
Margin Trading x50 
Margin Trading x75 
Margin Trading x100 
Derivatives 
Prediction markets 
Web3 Inteegration 
DAO 
P2P Trading 
Trading bots 
Layer Zero	

### Legal:
KYC 
KYB 
Legal Opinion 
SEC Transparency 
Anti Money Laundering 
Licence UAE 
Licence Europe 
Licence Asia 
Licence South America 
Licence Australia 
Licence North America 
Licence Nigeria 
Licence Japan 
Licence Ethiopia 
Licence India 
Licence Bangladesh 
Licence Indonesia 
Licence Vietnam 
Licence Turkey 
Licence Philippines	

### Web3
DEX 
Oracle 
Vesting Smartcontracts 
Launchpad 
NFT Marketplace 
Grant for Developers 
NFT Marketplace 
Crypto Farming 
Sport Collectibles Marketplace 
Market Making 
Web3 Advertising Platform	

### Specials:
WEB3 academy launch 
YouTube Gold Button 
Hamster YouTube Channel 
Bitcoin Pizza Day 
Top 10 Global 
Special Hamster 
TON + Hamster 
Consensus Piranha 
There are 2 chairs 
Apps Center 
USDT on TON 
Short Squeeze 
NFT Collection 
Villa for DEV 
Hamster Kombat Merch 
Bogdanoff 
Premarket 
Long Squeeze 
TG Leaders 
25 mio Youtube 
Green Energy 
X 10 mio 
Web3 game com 
Hamster daily show 
21,000,000 CEOs 
Hamster AI 
Notcoin listing 
Venom Blockchain 
Ad contract with a football club 
Token2049 
Dubai April 15-17 
Hamsters break records 
Sports integration 
Sports integration2 
Sports integration3 
Hamsters break records 
CX Hub Istanbul 
Quatrefinals are coming 
Quatrefinals are coming2 
Only 4 best left 
Semi-final Spain vs France 
250M Hamster players 
Final England vs Spain 
Buisness jet 
HamsterWatch for soulmate 
HamsterStore launch 
fight fight fight 
50M Telegram channel 
Hamster Analytics 
Strategic session in Australia 
Telegram Miniapp launch 
Kamala is calling 
Bitcoin conference 2024 
Telegram Stars integration 
The water is clear 
Carry it like it's hot 
HamsterBank 
Ethereum birthday 
This is fine 
HamsterGPT 
Games in Paris

**Comment by NabiKAZ** [comment]
Thanks for your comment.

You are right about the delay and the reason is that it is done manually and I am alone and no one is contributing to the update. I've always said that anyone can find the cards in the channels and update this project early so we can all use it together. Even yourself.
Of course, morse code and some things can be automated, but some things like cards cannot.

The second issue, because this project is for programming purposes, we used ID cards here and not their titles. In order to reach the title and more details of the cards, you just need to make a request to https://api.hamsterkombatgame.io/clicker/upgrades-for-buy and get the list of all cards and with a simple ID search on them, to its details. The card arrived.

**Comment by zuo305** [comment]
Hi @NabiKAZ , thank a lot for this project. You mentioned the cards info is manually, I am wondering how you get the card info? I might gave some contributing in the future.

**Comment by zuo305** [comment]
We might find some ways read the cards info from channel like python bot, then send it to your db.

**Comment by NabiKAZ** [comment]
You see, technically, all the processes can be done automatically by robots and the cards can also be discovered. I have done this for the Rocky Rabbit Enigma and Card Challenge, which are automatically and instantly sent to the Telegram group:
Rocky Rabbit combo cards:
https://t.me/BotSoratiMonitor/222234
Rocky Rabbit Wallet Keys:
https://t.me/BotSoratiMonitor/220188
Or this one Live tapswap code:
https://t.me/BotSoratiMonitor/217578

The same can be done about hamsters and it can be automated. But the thing about the hamster card is that it needs to be upgraded and I don't have enough coins in my accounts to upgrade all the cards once a day to find the desired cards. If the necessary resources are available, it can be automated.
As a result, I am currently taking daily cards from public channels, which are very large in number, and updating this API project for consumption by other robots. If you search the hamster tag in the Telegram search, you will find many channels.
After you find the cards, you can update and participate in this project for others to use and register a pull request.

At the same time, reading from the channels is also not cost-effective because they are all in the form of pictures and require costly and error-prone image processing.

I'm planning to add some other things to this project, such as tapeswap cinema codes, etc., which are on videos and almost impossible for robots to detect, and are best used collaboratively by humans and programmers, each providing a piece of the puzzle. Solve and share with others.

**Comment by DoctorGuidance** [comment]
> You see, technically, all the processes can be done automatically by robots and the cards can also be discovered. I have done this for the Rocky Rabbit Enigma and Card Challenge, which are automatically and instantly sent to the Telegram group: Rocky Rabbit combo cards: https://t.me/BotSoratiMonitor/222234 Rocky Rabbit Wallet Keys: https://t.me/BotSoratiMonitor/220188 Or this one Live tapswap code: https://t.me/BotSoratiMonitor/217578
> 
> The same can be done about hamsters and it can be automated. But the thing about the hamster card is that it needs to be upgraded and I don't have enough coins in my accounts to upgrade all the cards once a day to find the desired cards. If the necessary resources are available, it can be automated. As a result, I am currently taking daily cards from public channels, which are very large in number, and updating this API project for consumption by other robots. If you search the hamster tag in the Telegram search, you will find many channels. After you find the cards, you can update and participate in this project for others to use and register a pull request.
> 
> At the same time, reading from the channels is also not cost-effective because they are all in the form of pictures and require costly and error-prone image processing.
> 
> I'm planning to add some other things to this project, such as tapeswap cinema codes, etc., which are on videos and almost impossible for robots to detect, and are best used collaboratively by humans and programmers, each providing a piece of the puzzle. Solve and share with others.

the online sites place them too,
so I will scraping those and take out the class or the tag of that part, and read the cards, then add my bot to channel to post them in first minutes (maximum 30m), you can follow my channel: t.me/HamsterGuidance

I'm busy on some projects now. It take many hours to build this feature it is not on my priority now.

**Comment by zuo305** [comment]
Actually I already made one, now it is working well. I do not know how to share to you guys, you might give me a api, I could send it every day. This is my twritter and it update the code and mini game video every day.
https://x.com/chinazuo305

**Comment by NabiKAZ** [comment]
> 
> the online sites place them too, so I will scraping those and take out the class or the tag of that part, and read the cards, then add my bot to channel to post them in first minutes (maximum 30m), you can follow my channel: t.me/HamsterGuidance
> 
> I'm busy on some projects now. It take many hours to build this feature it is not on my priority now.

Can you please give me a web resource to get the ID of the daily combocards, maybe I can write the scratch code for it.
Although, in the end, either your channel or those websites update it manually, and this means depending on other people's code, which is not interesting.

**Comment by NabiKAZ** [comment]
> Actually I already made one, now it is working well. I do not know how to share to you guys, you might give me a api, I could send it every day. This is my twritter and it update the code and mini game video every day. https://x.com/chinazuo305

I doubt you have it automated.
If you are truly automating combo cards, you should provide an API to receive them, not me providing an API for you to post. If you are considering something like this, you can directly post to GitHub to commit to this project.
If it is not automatic and you do it manually, then you can still commit manually in the same project.
